-- NJRP ePCR Supabase schema + starter seed
-- Run this in Supabase Dashboard -> SQL Editor -> New query.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  username text not null unique,
  password_hash text not null,
  role text not null check (role in ('Provider', 'Supervisor', 'Admin')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.pcr_reports (
  id bigint generated by default as identity primary key,
  pcr_id text not null unique,
  cad_number text,
  owner_id bigint not null references public.users(id),
  status text not null check (status in ('Draft', 'Returned', 'Submitted', 'Approved', 'Locked')),
  incident_type text,
  unit text,
  priority text,
  incident_date date,
  incident jsonb not null default '{}'::jsonb,
  patient jsonb not null default '{}'::jsonb,
  times jsonb not null default '{}'::jsonb,
  assessment jsonb not null default '{}'::jsonb,
  narrative jsonb not null default '{}'::jsonb,
  vitals jsonb not null default '[]'::jsonb,
  medications jsonb not null default '[]'::jsonb,
  interventions jsonb not null default '[]'::jsonb,
  signatures jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now(),
  submitted_at timestamptz,
  approved_at timestamptz,
  locked_at timestamptz
);

create table if not exists public.qa_comments (
  id bigint generated by default as identity primary key,
  report_id bigint not null references public.pcr_reports(id) on delete cascade,
  user_id bigint not null references public.users(id),
  comment text not null,
  type text not null default 'Comment',
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id),
  report_id bigint references public.pcr_reports(id) on delete set null,
  action text not null,
  detail text,
  created_at timestamptz not null default now()
);

create table if not exists public.refusal_reports (
  id bigint generated by default as identity primary key,
  refusal_id text not null unique,
  owner_id bigint not null references public.users(id),
  status text not null default 'Draft',
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create index if not exists idx_users_username_lower on public.users (lower(username));
create index if not exists idx_pcr_reports_owner on public.pcr_reports (owner_id);
create index if not exists idx_pcr_reports_status on public.pcr_reports (status);
create index if not exists idx_pcr_reports_updated_at on public.pcr_reports (updated_at desc);
create index if not exists idx_qa_comments_report on public.qa_comments (report_id, created_at desc);
create index if not exists idx_audit_logs_created_at on public.audit_logs (created_at desc);

alter table public.users disable row level security;
alter table public.pcr_reports disable row level security;
alter table public.qa_comments disable row level security;
alter table public.audit_logs disable row level security;
alter table public.refusal_reports disable row level security;

insert into public.users (name, email, username, password_hash, role, active)
values
  ('Jordan Reyes', 'provider@njrp.local', 'ProviderDemo', '9b2c10630357580c811cc0ffa701ac91901c9075b00dd0e0c9cb240b7b27f898', 'Provider', true)
on conflict (username) do update set
  name = excluded.name,
  email = excluded.email,
  password_hash = excluded.password_hash,
  role = excluded.role,
  active = true;

insert into public.users (name, email, username, password_hash, role, active)
values
  ('NJRP Master', 'master@njrp.local', 'Yoroblox372', '95d2618158435c9cf2066ac414f5c675bedee1156225f91d34790d09fcf10942', 'Admin', true)
on conflict (email) do update set
  name = excluded.name,
  username = excluded.username,
  password_hash = excluded.password_hash,
  role = excluded.role,
  active = true;

with provider as (
  select id from public.users where username = 'ProviderDemo' limit 1
)
insert into public.pcr_reports (
  pcr_id, cad_number, owner_id, status, incident_type, unit, priority, incident_date,
  incident, patient, times, assessment, narrative, vitals, medications, interventions, signatures, updated_at
)
select
  'PCR-2026-10021',
  'CAD-260623-0412',
  provider.id,
  'Draft',
  'Chest Pain',
  'Medic 12',
  '1-Emergent',
  '2026-06-23',
  '{"pcrId":"PCR-2026-10021","cadNumber":"CAD-260623-0412","unit":"Medic 12","crew":"J. Reyes, EMT-P / S. Cole, EMT","primaryProvider":"Jordan Reyes","agencies":"NJRP EMS, County Fire, Local Law Enforcement","incidentType":"Chest Pain","priority":"1-Emergent","incidentDate":"2026-06-23","status":"Draft"}'::jsonb,
  '{"patientName":"Avery Thompson","age":64,"dob":"1966-04-12","sex":"Male","weight":"82 kg","chiefComplaint":"Chest pressure","allergies":"NKDA","medications":"See medication list","pastMedicalHistory":"Hypertension"}'::jsonb,
  '{"dispatched":"08:32","enroute":"08:35","onScene":"08:42","patientContact":"08:45","departScene":"09:08","atDestination":"09:24","transferOfCare":"09:39","available":"09:54"}'::jsonb,
  '{"mentalStatus":"Alert and oriented x4","avpu":"Alert","gcs":"15","airway":"Patent","breathing":"Even and unlabored","circulation":"Radial pulses strong and regular","skin":"Warm, dry, normal color","pupils":"PERRL 3 mm","lungSounds":"Clear bilaterally","painScale":"7/10","impression":"Chest Pain","physicalExam":"No obvious trauma. Head-to-toe assessment completed without additional acute findings.","opqrst":"Onset with activity; pressure-like; non-radiating; 7/10; began 30 minutes prior.","sample":"Symptoms as documented; NKDA; medications reviewed; last oral intake 0700; event while walking."}'::jsonb,
  '{"dispatch":"Dispatched priority one for chest pressure.","arrival":"Crew arrived to find patient seated, alert, and tracking EMS.","assessment":"Primary and secondary assessments completed. Findings documented above.","treatment":"Patient monitored continuously. Treatments provided per protocol with reassessment.","transport":"Transported without incident. Care transferred with bedside report.","full":"Unit Medic 12 responded for chest pressure. Patient was assessed, treated per NJRP protocol, and transported in a position of comfort. Serial vital signs obtained and documented. No deterioration noted during transport."}'::jsonb,
  '[{"time":"08:48","hr":108,"sys":168,"dia":96,"rr":22,"spo2":94,"etco2":36,"temp":98.4,"bgl":112,"pain":7,"gcs":15,"rhythm":"Sinus tach","notes":"Initial"},{"time":"09:06","hr":92,"sys":148,"dia":86,"rr":18,"spo2":97,"etco2":38,"temp":98.4,"bgl":112,"pain":3,"gcs":15,"rhythm":"NSR","notes":"Post NTG"}]'::jsonb,
  '[{"medication":"Aspirin","dose":"324 mg","route":"PO","time":"08:52","indication":"Suspected ACS","contraindications":"Checked","response":"No adverse response","administeredBy":"J. Reyes","notes":""},{"medication":"Nitroglycerin","dose":"0.4 mg","route":"SL","time":"08:57","indication":"Chest pain","contraindications":"Checked","response":"Pain reduced to 3/10","administeredBy":"J. Reyes","notes":""}]'::jsonb,
  '[{"intervention":"12-lead ECG","time":"08:50","successful":"Yes","performedBy":"J. Reyes","response":"Sinus tachycardia, no STEMI criteria","notes":"Transmitted"},{"intervention":"IV access","time":"08:54","successful":"Yes","performedBy":"J. Reyes","response":"18g left AC","notes":"Saline lock"}]'::jsonb,
  '[]'::jsonb,
  '2026-06-23T08:42:00.000Z'
from provider
on conflict (pcr_id) do nothing;
